# SPDX-License-Identifier: LGPL-2.1-or-later

#
# This file is part of libgpiod.
#
# Copyright (C) 2022 Bartosz Golaszewski <bartekgola@gmail.com>
#
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  # doxygen is available by default, but just in case.
  # others are definitely missing.
  apt_packages:
      - autoconf
      - autoconf-archive
      - libtool
      - m4
      - doxygen
      - graphviz

sphinx:
   configuration: sphinx/conf.py

